# Mane, R., Chew, E., Chua, K., Ang, K. K., Robinson, N., Vinod, A. P.,
# et al. (2021). FBCNet: a multi-view convolutional neural network for
# brain-computer interface. arXiv preprint. doi: 10.48550/arXiv.2104.01233
# TODO not yet implemented