# Arı, E., & Taçgın, E. (2024). NF-EEG: A generalized CNN model for multi class
# EEG motor imagery classification without signal preprocessing for brain
# computer interfaces. Biomedical Signal Processing and Control, 92, 106081.
# TODO not yet implemented